# Setup
title:               Heat forecast for Paris 2024
tagline:             'Olympic Games'
description:         'A heat forecast for the Paris 2024 Olympics based on feels-like temperatures by ECMWF, run by Milan Klöwer.'
url:                 http://heatforecast.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Milan Klöwer
  url:               https://github.com/milankl
  email:             milankloewer@gmx.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
