# Setup
title:               Heat Forecast
tagline:             'for Paris 2024 Olympics'
description:         'A heat forecast based on feels-like temperatures forecast by ECMWF, run by Milan Kloewer.'
url:                 http://heatforecast.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Milan Kloewer
  url:               https://github.com/milankl
  email:             milankloewer@gmx.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
